//! Certificate rotation: a live, hot-swappable certificate behind the TLS listener, and the
//! background work that keeps it from expiring.
//!
//! **The gap this closes.** Up to 0.4.0 the listener built one `ServerConfig` at boot from the PEM
//! pair on disk and kept it for the life of the process. Nothing renewed an ACME certificate, nothing
//! regenerated a self-signed one, and a certificate replaced on disk by cert-manager, Vault Agent or
//! certbot was ignored until someone restarted the proxy. Every one of those ends the same way: a
//! running proxy serving an expired certificate it could have replaced.
//!
//! Three pieces, each usable on its own:
//!
//! * [`CertStore`] — the certificate the listener serves, behind an [`ArcSwap`]. It implements
//!   rustls's [`ResolvesServerCert`], so every *new* handshake reads the current pair while
//!   connections already established keep the one they negotiated. Swapping drops nothing.
//! * [`watch`] — reloads the store when the files change on disk, whoever changed them. A pair that
//!   does not load (unparseable, or a key that does not match the certificate) is rejected and the
//!   previous one keeps serving — the same contract as config hot-reload.
//! * [`maintain`] — renews before expiry when this process is the certificate's source: ACME
//!   (`[tls.acme]`) or self-signed (`[tls] self_signed`). It renews at two-thirds of the
//!   certificate's lifetime — day 60 of a 90-day certificate — so a failed attempt leaves a month of
//!   retries before anything expires.
//!
//! Renewal writes through [`crate::selfsigned::publish_pair`], the same all-or-nothing pair writer
//! first-boot generation uses, and then reloads the store. The watcher would pick the files up
//! anyway; reloading directly means renewal does not depend on filesystem notifications working
//! (they do not on some network filesystems).
//!
//! **Dependency note.** Certificate validity is read by the small DER walker at the bottom of this
//! file rather than an X.509 crate: the proxy needs two dates, a serial and one comparison, and
//! `x509-parser` is not otherwise in this crate's graph.

use std::fmt;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Arc, Mutex};
use std::time::Duration;

use anyhow::{Context, Result};
use arc_swap::ArcSwap;
use notify::{Event, EventKind, RecursiveMode, Watcher};
use rustls::server::{ClientHello, ResolvesServerCert};
use rustls::sign::CertifiedKey;
use serde::Serialize;
use tokio::sync::{mpsc, watch as tokio_watch};
use tracing::{debug, error, info, warn};

use crate::config::TlsCfg;

/// How often [`maintain`] re-checks the certificate when nothing is wrong. Hourly is far finer than
/// any renewal window (the shortest public certificates are days long) and costs one file read.
const CHECK_EVERY: Duration = Duration::from_secs(60 * 60);
/// Spread added to [`CHECK_EVERY`], so a fleet started together does not renew together and hit
/// the CA — or the control plane's lease endpoint — in the same second.
const CHECK_JITTER_SECS: u64 = 10 * 60;
/// Longest wait between retries after failed renewals. Short enough that a renewal which keeps
/// failing for a day still gets a dozen more attempts inside the month the ⅔ rule leaves.
const MAX_BACKOFF: Duration = Duration::from_secs(12 * 60 * 60);
/// Below this many days left, an unrenewable certificate is warned about on every check rather
/// than once.
const URGENT_DAYS: i64 = 7;

/// Where the served certificate comes from, which decides what — if anything — renews it.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum CertSource {
    /// Issued over ACME by this process.
    Acme,
    /// Generated by this process (`tls.self_signed`).
    SelfSigned,
    /// Provided by the operator or another tool; this process only reloads it.
    File,
}

impl CertSource {
    /// The source implied by the TLS config.
    pub fn from_cfg(tls: &TlsCfg) -> Self {
        if tls.acme.enabled {
            CertSource::Acme
        } else if tls.self_signed {
            CertSource::SelfSigned
        } else {
            CertSource::File
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            CertSource::Acme => "acme",
            CertSource::SelfSigned => "self_signed",
            CertSource::File => "file",
        }
    }
}

/// What the listener is serving right now — for metrics, `doctor` and `GET /__edgeguard/tls`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
pub struct CertInfo {
    /// Start of validity, unix seconds.
    pub not_before: i64,
    /// End of validity, unix seconds.
    pub not_after: i64,
    /// Serial number, lowercase hex.
    pub serial: String,
    /// Issuer and subject are the same name: a self-signed (or otherwise self-issued) certificate.
    /// Self-signed renewal only ever replaces a certificate that is self-issued, so an operator's
    /// own CA-issued certificate at the same path is never overwritten.
    pub self_issued: bool,
}

impl CertInfo {
    /// Parse the validity window and identity fields out of a DER-encoded certificate.
    pub fn from_der(der: &[u8]) -> Result<Self> {
        der::parse(der)
    }

    /// Whole days until `not_after` (negative once expired).
    pub fn days_left(&self, now: i64) -> i64 {
        (self.not_after - now).div_euclid(86_400)
    }
}

/// Is a certificate valid from `not_before` to `not_after` due for renewal at `now`?
///
/// Due once two-thirds of its lifetime has passed: day 60 of a 90-day certificate, matching the
/// renewal point Let's Encrypt recommends, and leaving a third of the lifetime to retry in. A
/// certificate with no positive lifetime (garbled dates) is always due — renewing it is the only
/// way it gets fixed.
pub fn renewal_due(not_before: i64, not_after: i64, now: i64) -> bool {
    let lifetime = not_after - not_before;
    if lifetime <= 0 {
        return true;
    }
    now >= not_before + lifetime / 3 * 2
}

/// Result of a [`CertStore::reload`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Reload {
    /// The files hold the pair already being served.
    Unchanged,
    /// A different pair loaded and is now served to new handshakes.
    Swapped,
}

struct Live {
    key: Arc<CertifiedKey>,
    info: CertInfo,
}

/// Renewal `outcome` label values on `edgeguard_tls_cert_renewals_total`.
const RENEW_OUTCOMES: [&str; 3] = ["ok", "failed", "deferred"];
/// Renewal `source` label values (only sources this process renews).
const RENEW_SOURCES: [&str; 2] = ["acme", "self_signed"];

/// The last renewal attempt, for `GET /__edgeguard/tls`.
#[derive(Clone, Debug, Serialize)]
pub struct RenewalRecord {
    pub at: i64,
    pub source: &'static str,
    pub outcome: &'static str,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

/// The certificate the TLS listener serves, swappable while it runs.
pub struct CertStore {
    cert_path: String,
    key_path: String,
    source: CertSource,
    live: ArcSwap<Live>,
    reloads_swapped: AtomicU64,
    reloads_rejected: AtomicU64,
    /// `RENEW_SOURCES.len() * RENEW_OUTCOMES.len()` counters, source-major.
    renewals: [AtomicU64; 6],
    last_renewal: Mutex<Option<RenewalRecord>>,
}

impl fmt::Debug for CertStore {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("CertStore")
            .field("cert_path", &self.cert_path)
            .field("key_path", &self.key_path)
            .field("source", &self.source)
            .field("info", &self.live.load().info)
            .finish()
    }
}

impl CertStore {
    /// Load the pair at `cert_path`/`key_path`. Fails if it cannot be served — the listener has
    /// nothing to fall back to at startup.
    pub fn load(cert_path: &str, key_path: &str, source: CertSource) -> Result<Arc<Self>> {
        let live = load_pair(cert_path, key_path)?;
        Ok(Arc::new(CertStore {
            cert_path: cert_path.to_string(),
            key_path: key_path.to_string(),
            source,
            live: ArcSwap::from_pointee(live),
            reloads_swapped: AtomicU64::new(0),
            reloads_rejected: AtomicU64::new(0),
            renewals: Default::default(),
            last_renewal: Mutex::new(None),
        }))
    }

    pub fn cert_path(&self) -> &str {
        &self.cert_path
    }

    pub fn key_path(&self) -> &str {
        &self.key_path
    }

    pub fn source(&self) -> CertSource {
        self.source
    }

    /// The certificate being served right now.
    pub fn info(&self) -> CertInfo {
        self.live.load().info.clone()
    }

    pub fn last_renewal(&self) -> Option<RenewalRecord> {
        self.last_renewal.lock().ok().and_then(|g| g.clone())
    }

    /// Re-read the files and, if they hold a different, valid pair, serve it to new handshakes.
    ///
    /// A pair that fails to load leaves the current one in place and returns the error. That
    /// includes the moment between another tool writing the certificate and writing its key: the
    /// half-written pair fails the key check, and the next change event (or the next hourly check)
    /// loads the completed one.
    pub fn reload(&self) -> Result<Reload> {
        let next = match load_pair(&self.cert_path, &self.key_path) {
            Ok(next) => next,
            Err(e) => {
                self.reloads_rejected.fetch_add(1, Ordering::Relaxed);
                return Err(e);
            }
        };
        if next.key.cert == self.live.load().key.cert {
            return Ok(Reload::Unchanged);
        }
        let info = next.info.clone();
        self.live.store(Arc::new(next));
        self.reloads_swapped.fetch_add(1, Ordering::Relaxed);
        info!(
            cert = %self.cert_path,
            serial = %info.serial,
            not_after = info.not_after,
            "TLS certificate reloaded; new handshakes use it"
        );
        Ok(Reload::Swapped)
    }

    fn record_renewal(&self, source: &'static str, outcome: &'static str, error: Option<String>) {
        if let (Some(s), Some(o)) = (
            RENEW_SOURCES.iter().position(|x| *x == source),
            RENEW_OUTCOMES.iter().position(|x| *x == outcome),
        ) {
            self.renewals[s * RENEW_OUTCOMES.len() + o].fetch_add(1, Ordering::Relaxed);
        }
        if let Ok(mut g) = self.last_renewal.lock() {
            *g = Some(RenewalRecord {
                at: now_unix(),
                source,
                outcome,
                error,
            });
        }
    }

    /// Prometheus text exposition for the certificate, appended to `/__edgeguard/metrics`.
    pub fn render_metrics(&self, out: &mut String) {
        let info = self.info();
        let source = self.source.label();
        out.push_str(
            "# HELP edgeguard_tls_cert_not_after_seconds Expiry of the served TLS certificate (unix seconds).\n\
             # TYPE edgeguard_tls_cert_not_after_seconds gauge\n",
        );
        out.push_str(&format!(
            "edgeguard_tls_cert_not_after_seconds{{source=\"{source}\"}} {}\n",
            info.not_after
        ));
        out.push_str(
            "# HELP edgeguard_tls_cert_not_before_seconds Start of validity of the served TLS certificate (unix seconds).\n\
             # TYPE edgeguard_tls_cert_not_before_seconds gauge\n",
        );
        out.push_str(&format!(
            "edgeguard_tls_cert_not_before_seconds{{source=\"{source}\"}} {}\n",
            info.not_before
        ));
        out.push_str(
            "# HELP edgeguard_tls_cert_reloads_total Certificate reloads from disk, by outcome.\n\
             # TYPE edgeguard_tls_cert_reloads_total counter\n",
        );
        out.push_str(&format!(
            "edgeguard_tls_cert_reloads_total{{outcome=\"swapped\"}} {}\n",
            self.reloads_swapped.load(Ordering::Relaxed)
        ));
        out.push_str(&format!(
            "edgeguard_tls_cert_reloads_total{{outcome=\"rejected\"}} {}\n",
            self.reloads_rejected.load(Ordering::Relaxed)
        ));
        out.push_str(
            "# HELP edgeguard_tls_cert_renewals_total Certificate renewal attempts, by source and outcome.\n\
             # TYPE edgeguard_tls_cert_renewals_total counter\n",
        );
        for (s, src) in RENEW_SOURCES.iter().enumerate() {
            for (o, outcome) in RENEW_OUTCOMES.iter().enumerate() {
                let v = self.renewals[s * RENEW_OUTCOMES.len() + o].load(Ordering::Relaxed);
                out.push_str(&format!(
                    "edgeguard_tls_cert_renewals_total{{source=\"{src}\",outcome=\"{outcome}\"}} {v}\n"
                ));
            }
        }
    }

    /// JSON body for `GET /__edgeguard/tls`.
    pub fn status_json(&self) -> serde_json::Value {
        let info = self.info();
        let now = now_unix();
        serde_json::json!({
            "source": self.source,
            "cert_path": self.cert_path,
            "serial": info.serial,
            "not_before": info.not_before,
            "not_after": info.not_after,
            "days_left": info.days_left(now),
            "self_issued": info.self_issued,
            "renewal_due": renewal_due(info.not_before, info.not_after, now),
            "last_renewal": self.last_renewal(),
        })
    }
}

impl ResolvesServerCert for CertStore {
    fn resolve(&self, _hello: ClientHello<'_>) -> Option<Arc<CertifiedKey>> {
        Some(Arc::clone(&self.live.load().key))
    }
}

/// Load and check a certificate pair: parseable, non-empty, and the key belongs to the leaf.
fn load_pair(cert_path: &str, key_path: &str) -> Result<Live> {
    let certs = crate::tls::load_certs(cert_path)?;
    let key = crate::tls::load_key(key_path)?;
    let info = CertInfo::from_der(&certs[0])
        .with_context(|| format!("reading the validity of the certificate in {cert_path}"))?;
    let signing = rustls::crypto::ring::sign::any_supported_type(&key)
        .with_context(|| format!("unsupported private key type in {key_path}"))?;
    let key = CertifiedKey::new(certs, signing);
    match key.keys_match() {
        Ok(()) => {}
        // The key type cannot report its public half, so there is nothing to compare; rustls
        // would have accepted this pair at boot too, and the handshake itself still proves it.
        Err(rustls::Error::InconsistentKeys(rustls::InconsistentKeys::Unknown)) => {}
        Err(e) => {
            return Err(anyhow::anyhow!(e)).with_context(|| {
                format!("the key in {key_path} does not match the certificate in {cert_path}")
            })
        }
    }
    Ok(Live {
        key: Arc::new(key),
        info,
    })
}

/// Reload `store` whenever its certificate or key file changes. Runs until `shutdown` flips.
///
/// Watches the parent *directories*, not the files, for the same reason config hot-reload does:
/// atomic writers replace a file by renaming over it, which drops a watch on the old inode. It
/// does not filter by file name either — a Kubernetes secret volume updates by flipping a `..data`
/// symlink, so the events name `..data`, not `tls.crt`. Reacting to every change in the directory
/// is safe because a reload of an unchanged pair is a no-op.
pub async fn watch(store: Arc<CertStore>, mut shutdown: tokio_watch::Receiver<bool>) -> Result<()> {
    let (tx, mut rx) = mpsc::channel::<()>(8);
    let mut watcher = notify::recommended_watcher(move |res: notify::Result<Event>| match res {
        Ok(event) if !matches!(event.kind, EventKind::Access(_)) => {
            let _ = tx.try_send(());
        }
        Ok(_) => {}
        Err(e) => warn!(error = %e, "certificate watcher error"),
    })
    .context("creating certificate watcher")?;

    let mut dirs: Vec<PathBuf> = [store.cert_path(), store.key_path()]
        .iter()
        .map(|p| {
            Path::new(p)
                .parent()
                .filter(|d| !d.as_os_str().is_empty())
                .map(Path::to_path_buf)
                .unwrap_or_else(|| PathBuf::from("."))
        })
        .collect();
    dirs.dedup();
    for dir in &dirs {
        watcher
            .watch(dir, RecursiveMode::NonRecursive)
            .with_context(|| format!("watching {}", dir.display()))?;
    }
    info!(cert = %store.cert_path(), "certificate reload on change enabled");

    loop {
        tokio::select! {
            changed = shutdown.changed() => {
                if changed.is_err() || *shutdown.borrow() { break; }
            }
            tick = rx.recv() => {
                if tick.is_none() { break; }
                // Writers emit a burst of events per update (and two tools may write the cert and
                // key separately); settle before reading.
                tokio::time::sleep(Duration::from_millis(500)).await;
                while rx.try_recv().is_ok() {}
                match store.reload() {
                    Ok(_) => {}
                    Err(e) => warn!(
                        error = format!("{e:#}"),
                        "certificate files changed but do not load; still serving the previous certificate"
                    ),
                }
            }
        }
    }
    drop(watcher);
    Ok(())
}

/// What renews the served certificate. Decided once from config.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RenewPlan {
    Acme,
    SelfSigned,
    /// Nothing in this process renews it; [`maintain`] only reloads and warns.
    None,
}

impl RenewPlan {
    pub fn from_cfg(tls: &TlsCfg) -> Self {
        if tls.acme.enabled && tls.acme.renew {
            RenewPlan::Acme
        } else if !tls.acme.enabled && tls.self_signed && tls.self_signed_renew {
            RenewPlan::SelfSigned
        } else {
            RenewPlan::None
        }
    }
}

/// Everything [`maintain`] needs to renew.
pub struct Renewer {
    pub store: Arc<CertStore>,
    pub tls: TlsCfg,
    pub plan: RenewPlan,
    /// Managed-mode client: in managed mode the control plane holds the CA's shared rate limits.
    pub cp: Option<Arc<crate::cp::CpClient>>,
    /// When the redirect listener holds the HTTP-01 port, renewal publishes its challenge tokens
    /// here for that listener to answer, instead of trying to bind the port a second time.
    pub challenges: Option<crate::acme::ChallengeMap>,
}

/// What one renewal check did.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Check {
    NotDue,
    Renewed,
    /// Due, but the issuance budget refused; try later.
    Deferred,
    /// Due, and nothing in this process can renew it.
    Unrenewable,
}

impl Renewer {
    /// Renew now if the served certificate is due. Errors are failed renewal attempts.
    pub async fn check(&self) -> Result<Check> {
        let info = self.store.info();
        let now = now_unix();
        if !renewal_due(info.not_before, info.not_after, now) {
            return Ok(Check::NotDue);
        }
        match self.plan {
            RenewPlan::Acme => {
                info!(
                    domains = ?self.tls.acme.domains,
                    days_left = info.days_left(now),
                    "ACME certificate is due for renewal"
                );
                let result = crate::acme::obtain_certificate_via(
                    &self.tls.acme,
                    &self.tls,
                    self.cp.as_deref(),
                    self.challenges.as_ref(),
                )
                .await;
                match result {
                    Ok(crate::acme::Issuance::Issued) => {
                        self.store
                            .reload()
                            .context("loading the renewed certificate")?;
                        self.store.record_renewal("acme", "ok", None);
                        Ok(Check::Renewed)
                    }
                    Ok(crate::acme::Issuance::Deferred { retry_at_unix, .. }) => {
                        warn!(
                            retry_at_unix,
                            days_left = info.days_left(now),
                            "ACME renewal deferred by the issuance budget; still serving the current certificate"
                        );
                        self.store.record_renewal("acme", "deferred", None);
                        Ok(Check::Deferred)
                    }
                    Err(e) => {
                        self.store
                            .record_renewal("acme", "failed", Some(format!("{e:#}")));
                        Err(e)
                    }
                }
            }
            RenewPlan::SelfSigned => {
                if !info.self_issued {
                    // Someone put a CA-issued certificate at this path. Overwriting it with a
                    // self-signed one would downgrade trust, so leave it alone and say why.
                    warn!(
                        cert = %self.store.cert_path(),
                        "certificate is due for renewal but is not self-signed; self-signed \
                         renewal will not overwrite it"
                    );
                    return Ok(Check::Unrenewable);
                }
                let renewed = crate::selfsigned::renew(
                    &self.tls.self_signed_host_list(),
                    self.tls.self_signed_days,
                    self.store.cert_path(),
                    self.store.key_path(),
                    !self.tls.self_signed_rotate_key,
                )
                .and_then(|()| {
                    self.store
                        .reload()
                        .context("loading the renewed certificate")
                });
                match renewed {
                    Ok(_) => {
                        self.store.record_renewal("self_signed", "ok", None);
                        Ok(Check::Renewed)
                    }
                    Err(e) => {
                        self.store
                            .record_renewal("self_signed", "failed", Some(format!("{e:#}")));
                        Err(e)
                    }
                }
            }
            RenewPlan::None => Ok(Check::Unrenewable),
        }
    }
}

/// Keep the served certificate current until `shutdown` flips: re-read the files, and renew when
/// due. Checks once immediately, so a certificate already past its renewal point at startup (a
/// 0.4.0 self-signed certificate on its 70th day, say) is renewed now rather than in an hour.
pub async fn maintain(renewer: Renewer, mut shutdown: tokio_watch::Receiver<bool>) {
    let mut failures: u32 = 0;
    let mut warned_unrenewable = false;
    info!(
        plan = ?renewer.plan,
        source = renewer.store.source().label(),
        "certificate renewal checks enabled"
    );
    loop {
        // Pick up a pair replaced by anything else first, so the due-check below looks at what is
        // actually on disk. The watcher normally gets there first; this is the backstop for
        // filesystems that deliver no change events.
        if let Err(e) = renewer.store.reload() {
            debug!(
                error = format!("{e:#}"),
                "periodic certificate reload rejected"
            );
        }

        match renewer.check().await {
            Ok(Check::NotDue) | Ok(Check::Renewed) => {
                failures = 0;
                warned_unrenewable = false;
            }
            Ok(Check::Deferred) => failures = failures.saturating_add(1),
            Ok(Check::Unrenewable) => {
                let info = renewer.store.info();
                let days_left = info.days_left(now_unix());
                if !warned_unrenewable || days_left < URGENT_DAYS {
                    warn!(
                        cert = %renewer.store.cert_path(),
                        days_left,
                        not_after = info.not_after,
                        "the TLS certificate is past two-thirds of its lifetime and nothing in this \
                         process renews it; replace the files (they are reloaded automatically)"
                    );
                    warned_unrenewable = true;
                }
            }
            Err(e) => {
                failures = failures.saturating_add(1);
                error!(
                    error = format!("{e:#}"),
                    attempt = failures,
                    "certificate renewal failed; still serving the current certificate"
                );
            }
        }

        let wait = if failures == 0 {
            CHECK_EVERY + Duration::from_secs(jitter_secs(CHECK_JITTER_SECS))
        } else {
            backoff(failures)
        };
        tokio::select! {
            _ = tokio::time::sleep(wait) => {}
            changed = shutdown.changed() => {
                if changed.is_err() || *shutdown.borrow() { return; }
            }
        }
    }
}

/// Retry delay after `failures` consecutive failed attempts: 5 minutes, doubling, capped at
/// [`MAX_BACKOFF`].
pub fn backoff(failures: u32) -> Duration {
    let base = Duration::from_secs(5 * 60);
    let factor = 1u32 << failures.saturating_sub(1).min(16);
    (base * factor).min(MAX_BACKOFF)
}

fn jitter_secs(max: u64) -> u64 {
    if max == 0 {
        return 0;
    }
    (uuid::Uuid::new_v4().as_u128() % u128::from(max)) as u64
}

fn now_unix() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs() as i64)
        .unwrap_or(0)
}

/// Minimal DER reading for an X.509 certificate: the validity window, the serial, and whether
/// issuer equals subject. Not a validator — rustls and the client do the validating; this only
/// reads fields out of a certificate the TLS stack has already accepted as loadable.
mod der {
    use anyhow::{bail, ensure, Context, Result};

    use super::CertInfo;

    const SEQUENCE: u8 = 0x30;
    const INTEGER: u8 = 0x02;
    const UTC_TIME: u8 = 0x17;
    const GENERALIZED_TIME: u8 = 0x18;
    const EXPLICIT_0: u8 = 0xa0;

    /// One TLV: tag, contents, the whole encoding (header included), and what follows it.
    struct Tlv<'a> {
        tag: u8,
        value: &'a [u8],
        whole: &'a [u8],
        rest: &'a [u8],
    }

    fn read(input: &[u8]) -> Result<Tlv<'_>> {
        ensure!(input.len() >= 2, "truncated DER");
        let tag = input[0];
        let first = input[1];
        let (len, header) = if first < 0x80 {
            (usize::from(first), 2)
        } else {
            let n = usize::from(first & 0x7f);
            ensure!((1..=4).contains(&n), "unsupported DER length encoding");
            ensure!(input.len() >= 2 + n, "truncated DER length");
            let len = input[2..2 + n]
                .iter()
                .fold(0usize, |acc, b| (acc << 8) | usize::from(*b));
            (len, 2 + n)
        };
        let end = header.checked_add(len).context("DER length overflow")?;
        ensure!(
            input.len() >= end,
            "DER value runs past the end of its container"
        );
        Ok(Tlv {
            tag,
            value: &input[header..end],
            whole: &input[..end],
            rest: &input[end..],
        })
    }

    fn expect<'a>(input: &'a [u8], tag: u8, what: &str) -> Result<Tlv<'a>> {
        let tlv = read(input).with_context(|| format!("reading {what}"))?;
        ensure!(
            tlv.tag == tag,
            "expected {what} (tag {tag:#04x}), found tag {:#04x}",
            tlv.tag
        );
        Ok(tlv)
    }

    pub(super) fn parse(der: &[u8]) -> Result<CertInfo> {
        let cert = expect(der, SEQUENCE, "Certificate")?;
        let tbs = expect(cert.value, SEQUENCE, "TBSCertificate")?;
        let mut cur = tbs.value;
        // `version` is an optional explicit [0]; v1 certificates omit it.
        if cur.first() == Some(&EXPLICIT_0) {
            cur = read(cur)?.rest;
        }
        let serial = expect(cur, INTEGER, "serialNumber")?;
        let sig = expect(serial.rest, SEQUENCE, "signature AlgorithmIdentifier")?;
        let issuer = expect(sig.rest, SEQUENCE, "issuer")?;
        let validity = expect(issuer.rest, SEQUENCE, "validity")?;
        let subject = expect(validity.rest, SEQUENCE, "subject")?;

        let not_before = read(validity.value).context("reading notBefore")?;
        let not_after = read(not_before.rest).context("reading notAfter")?;

        Ok(CertInfo {
            not_before: time_to_unix(not_before.tag, not_before.value)?,
            not_after: time_to_unix(not_after.tag, not_after.value)?,
            serial: serial.value.iter().map(|b| format!("{b:02x}")).collect(),
            self_issued: issuer.whole == subject.whole,
        })
    }

    /// `UTCTime` (`YYMMDDHHMMSSZ`) or `GeneralizedTime` (`YYYYMMDDHHMMSSZ`) to unix seconds. RFC
    /// 5280 requires both in UTC with seconds and no fractions, which is all this accepts.
    fn time_to_unix(tag: u8, value: &[u8]) -> Result<i64> {
        // ASCII, not merely UTF-8: the fields below are sliced by byte offset, and a multi-byte
        // character straddling an offset would panic instead of returning this error. The bytes
        // come from a file on disk that nothing has validated yet — a panic here would kill the
        // watcher or renewal task, or the process at startup.
        ensure!(value.is_ascii(), "certificate time is not ASCII");
        let s = std::str::from_utf8(value).context("certificate time is not ASCII")?;
        let (year, rest) = match tag {
            UTC_TIME => {
                ensure!(s.len() == 13, "malformed UTCTime {s:?}");
                let yy: i32 = num(&s[0..2])?;
                // RFC 5280 §4.1.2.5.1: 50–99 are 19xx, 00–49 are 20xx.
                (if yy >= 50 { 1900 + yy } else { 2000 + yy }, &s[2..])
            }
            GENERALIZED_TIME => {
                ensure!(s.len() == 15, "malformed GeneralizedTime {s:?}");
                (num(&s[0..4])?, &s[4..])
            }
            other => bail!("unexpected time tag {other:#04x}"),
        };
        ensure!(rest.ends_with('Z'), "certificate time {s:?} is not UTC");
        let month = time::Month::try_from(num::<u8>(&rest[0..2])?)
            .with_context(|| format!("bad month in {s:?}"))?;
        let date = time::Date::from_calendar_date(year, month, num(&rest[2..4])?)
            .with_context(|| format!("bad date in {s:?}"))?;
        let clock = time::Time::from_hms(num(&rest[4..6])?, num(&rest[6..8])?, num(&rest[8..10])?)
            .with_context(|| format!("bad time of day in {s:?}"))?;
        Ok(time::PrimitiveDateTime::new(date, clock)
            .assume_utc()
            .unix_timestamp())
    }

    fn num<T: std::str::FromStr>(s: &str) -> Result<T> {
        ensure!(s.bytes().all(|b| b.is_ascii_digit()), "non-digit in {s:?}");
        s.parse::<T>()
            .map_err(|_| anyhow::anyhow!("number out of range: {s:?}"))
    }

    #[cfg(test)]
    mod tests {
        use super::*;

        #[test]
        fn utc_time_century_rule() {
            assert_eq!(
                time_to_unix(UTC_TIME, b"700101000000Z").unwrap(),
                0,
                "70 is 1970"
            );
            assert_eq!(
                time_to_unix(UTC_TIME, b"491231235959Z").unwrap(),
                2_524_607_999,
                "49 is 2049"
            );
            assert_eq!(
                time_to_unix(GENERALIZED_TIME, b"20500101000000Z").unwrap(),
                2_524_608_000
            );
        }

        #[test]
        fn rejects_garbage() {
            assert!(parse(&[]).is_err());
            assert!(parse(&[0x30, 0x05, 0x01]).is_err());
            assert!(time_to_unix(UTC_TIME, b"7001010000Z").is_err());
            assert!(time_to_unix(UTC_TIME, b"701301000000Z").is_err());
            assert!(time_to_unix(UTC_TIME, b"700101000000+").is_err());
            // Multi-byte UTF-8 with exactly the right BYTE length (13 / 15), placed so the "é"
            // straddles a slice boundary: byte-offset slicing would panic ("not a char boundary")
            // instead of returning an error.
            assert_eq!("7\u{e9}101000000Z".len(), 13);
            assert!(time_to_unix(UTC_TIME, "7\u{e9}101000000Z".as_bytes()).is_err());
            assert_eq!("202\u{e9}101000000Z".len(), 15);
            assert!(time_to_unix(GENERALIZED_TIME, "202\u{e9}101000000Z".as_bytes()).is_err());
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tmpdir(tag: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "eg-certstore-{tag}-{}-{}",
            std::process::id(),
            uuid::Uuid::new_v4().simple()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    fn hosts() -> Vec<String> {
        vec!["localhost".to_string()]
    }

    fn write_self_signed(dir: &Path, days: u32) -> (String, String) {
        let cert = dir.join("cert.pem").to_string_lossy().into_owned();
        let key = dir.join("key.pem").to_string_lossy().into_owned();
        crate::selfsigned::write_to(&hosts(), days, &cert, &key).unwrap();
        (cert, key)
    }

    #[test]
    fn reads_validity_and_self_issued_from_a_generated_certificate() {
        let dir = tmpdir("info");
        let (cert, key) = write_self_signed(&dir, 30);
        let store = CertStore::load(&cert, &key, CertSource::SelfSigned).unwrap();
        let info = store.info();
        let now = now_unix();
        assert!(info.self_issued);
        assert!(!info.serial.is_empty());
        // Backdated one hour, valid for 30 days.
        assert!((info.not_before - (now - 3600)).abs() < 120, "{info:?}");
        assert!(
            (info.not_after - (now + 30 * 86_400)).abs() < 120,
            "{info:?}"
        );
        // 29 or 30 depending on whether generation and `now` fall in the same second.
        assert!((29..=30).contains(&info.days_left(now)), "{info:?}");
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn renewal_point_is_two_thirds_of_the_lifetime() {
        let day = 86_400;
        assert!(!renewal_due(0, 90 * day, 59 * day));
        assert!(renewal_due(0, 90 * day, 60 * day));
        assert!(renewal_due(0, 90 * day, 100 * day));
        assert!(renewal_due(10, 10, 0), "no lifetime is always due");
    }

    #[test]
    fn backoff_doubles_and_caps() {
        assert_eq!(backoff(1), Duration::from_secs(300));
        assert_eq!(backoff(2), Duration::from_secs(600));
        assert_eq!(backoff(4), Duration::from_secs(2400));
        assert_eq!(backoff(30), MAX_BACKOFF);
    }

    #[test]
    fn reload_swaps_a_new_pair_and_rejects_a_mismatched_one() {
        let dir = tmpdir("reload");
        let (cert, key) = write_self_signed(&dir, 30);
        let store = CertStore::load(&cert, &key, CertSource::File).unwrap();
        let first = store.info();

        assert_eq!(store.reload().unwrap(), Reload::Unchanged);

        // A different valid pair is picked up.
        crate::selfsigned::write_to(&hosts(), 60, &cert, &key).unwrap();
        assert_eq!(store.reload().unwrap(), Reload::Swapped);
        let second = store.info();
        assert_ne!(first.serial, second.serial);

        // A certificate whose key does not match is refused; the previous pair keeps serving.
        let other = tmpdir("reload-other");
        let (other_cert, _) = write_self_signed(&other, 10);
        std::fs::copy(&other_cert, &cert).unwrap();
        assert!(store.reload().is_err());
        assert_eq!(store.info(), second);

        let mut metrics = String::new();
        store.render_metrics(&mut metrics);
        assert!(metrics.contains("edgeguard_tls_cert_reloads_total{outcome=\"swapped\"} 1"));
        assert!(metrics.contains("edgeguard_tls_cert_reloads_total{outcome=\"rejected\"} 1"));
        assert!(metrics.contains(&format!(
            "edgeguard_tls_cert_not_after_seconds{{source=\"file\"}} {}",
            second.not_after
        )));

        let _ = std::fs::remove_dir_all(&dir);
        let _ = std::fs::remove_dir_all(&other);
    }

    fn tls_cfg(cert: &str, key: &str) -> TlsCfg {
        TlsCfg {
            enabled: true,
            cert_path: cert.to_string(),
            key_path: key.to_string(),
            self_signed: true,
            ..Default::default()
        }
    }

    #[tokio::test]
    async fn self_signed_renewal_keeps_the_key_and_extends_validity() {
        let dir = tmpdir("renew");
        // One day of validity, back-dated an hour: about 4% through, so not yet due.
        let (cert, key) = write_self_signed(&dir, 1);
        let key_before = std::fs::read_to_string(&key).unwrap();
        let store = CertStore::load(&cert, &key, CertSource::SelfSigned).unwrap();
        let before = store.info();

        let mut tls = tls_cfg(&cert, &key);
        tls.self_signed_days = 90;
        let renewer = Renewer {
            store: Arc::clone(&store),
            plan: RenewPlan::from_cfg(&tls),
            tls,
            cp: None,
            challenges: None,
        };
        assert_eq!(renewer.plan, RenewPlan::SelfSigned);
        // Not due yet: nothing happens.
        assert_eq!(renewer.check().await.unwrap(), Check::NotDue);

        // Renew through the same function `check` calls once a certificate is due (the
        // due-path itself is covered by `due_self_signed_certificate_is_renewed_by_check`).
        crate::selfsigned::renew(&hosts(), 90, &cert, &key, true).unwrap();
        assert_eq!(store.reload().unwrap(), Reload::Swapped);
        let after = store.info();
        assert!(after.not_after > before.not_after + 80 * 86_400);
        assert_eq!(
            std::fs::read_to_string(&key).unwrap(),
            key_before,
            "renewal keeps the key by default"
        );

        // Rotating the key is opt-in.
        crate::selfsigned::renew(&hosts(), 90, &cert, &key, false).unwrap();
        assert_ne!(std::fs::read_to_string(&key).unwrap(), key_before);
        assert_eq!(store.reload().unwrap(), Reload::Swapped);

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[tokio::test]
    async fn due_self_signed_certificate_is_renewed_by_check() {
        let dir = tmpdir("due");
        let cert = dir.join("cert.pem").to_string_lossy().into_owned();
        let key = dir.join("key.pem").to_string_lossy().into_owned();
        // A certificate whose validity is entirely in the past is past any renewal point.
        let expired = expired_self_signed();
        crate::selfsigned::publish_pair(&expired.0, &expired.1, &cert, &key).unwrap();
        let store = CertStore::load(&cert, &key, CertSource::SelfSigned).unwrap();
        assert!(store.info().not_after < now_unix());

        let tls = tls_cfg(&cert, &key);
        let renewer = Renewer {
            store: Arc::clone(&store),
            plan: RenewPlan::from_cfg(&tls),
            tls,
            cp: None,
            challenges: None,
        };
        assert_eq!(renewer.check().await.unwrap(), Check::Renewed);
        assert!(store.info().not_after > now_unix() + 80 * 86_400);
        assert_eq!(store.last_renewal().unwrap().outcome, "ok");

        let mut metrics = String::new();
        store.render_metrics(&mut metrics);
        assert!(metrics.contains(
            "edgeguard_tls_cert_renewals_total{source=\"self_signed\",outcome=\"ok\"} 1"
        ));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[tokio::test]
    async fn self_signed_renewal_never_overwrites_a_ca_issued_certificate() {
        let dir = tmpdir("ca");
        let cert = dir.join("cert.pem").to_string_lossy().into_owned();
        let key = dir.join("key.pem").to_string_lossy().into_owned();
        let (leaf_pem, leaf_key) = expired_ca_issued();
        crate::selfsigned::publish_pair(&leaf_pem, &leaf_key, &cert, &key).unwrap();
        let store = CertStore::load(&cert, &key, CertSource::SelfSigned).unwrap();
        assert!(!store.info().self_issued);

        let tls = tls_cfg(&cert, &key);
        let renewer = Renewer {
            store: Arc::clone(&store),
            plan: RenewPlan::from_cfg(&tls),
            tls,
            cp: None,
            challenges: None,
        };
        assert_eq!(renewer.check().await.unwrap(), Check::Unrenewable);
        assert_eq!(std::fs::read_to_string(&cert).unwrap(), leaf_pem);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn plan_follows_config() {
        let mut tls = TlsCfg::default();
        assert_eq!(RenewPlan::from_cfg(&tls), RenewPlan::None);
        tls.self_signed = true;
        assert_eq!(RenewPlan::from_cfg(&tls), RenewPlan::SelfSigned);
        tls.self_signed_renew = false;
        assert_eq!(RenewPlan::from_cfg(&tls), RenewPlan::None);
        tls.acme.enabled = true;
        assert_eq!(RenewPlan::from_cfg(&tls), RenewPlan::Acme);
        tls.acme.renew = false;
        assert_eq!(RenewPlan::from_cfg(&tls), RenewPlan::None);
    }

    fn past(days_ago: i64) -> time::OffsetDateTime {
        time::OffsetDateTime::now_utc() - time::Duration::days(days_ago)
    }

    fn expired_self_signed() -> (String, String) {
        let mut params = rcgen::CertificateParams::new(hosts()).unwrap();
        params.not_before = past(100);
        params.not_after = past(10);
        let key = rcgen::KeyPair::generate().unwrap();
        let cert = params.self_signed(&key).unwrap();
        (cert.pem(), key.serialize_pem())
    }

    fn expired_ca_issued() -> (String, String) {
        let ca_key = rcgen::KeyPair::generate().unwrap();
        let mut ca_params = rcgen::CertificateParams::new(Vec::<String>::new()).unwrap();
        ca_params
            .distinguished_name
            .push(rcgen::DnType::CommonName, "Test CA");
        ca_params.is_ca = rcgen::IsCa::Ca(rcgen::BasicConstraints::Unconstrained);
        let ca = rcgen::CertifiedIssuer::self_signed(ca_params, ca_key).unwrap();

        let mut params = rcgen::CertificateParams::new(hosts()).unwrap();
        params
            .distinguished_name
            .push(rcgen::DnType::CommonName, "leaf");
        params.not_before = past(100);
        params.not_after = past(10);
        let key = rcgen::KeyPair::generate().unwrap();
        let cert = params.signed_by(&key, &ca).unwrap();
        (cert.pem(), key.serialize_pem())
    }
}
